version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # UI Web
      - "6831:6831/udp" # Thrift over UDP (agent)
      - "6832:6832/udp" # Thrift over UDP (agent)
      - "5778:5778"     # Configuration for clients
      - "4317:4317"     # OTLP gRPC receiver (você vai usar esse com o .NET)
      - "4318:4318"     # OTLP HTTP receiver (opcional)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_HTTP_ENABLED=true 
    networks:
      - jaeger-net

networks:
  jaeger-net:
    driver: bridge
